import { ArrowUpRight, CheckCircle2, Clock3, Sparkles, Target } from "lucide-react";
import { AreaChart, Area, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, BarChart, Bar } from "recharts";
import { Card, SectionHeader } from "../components/ui";
import { chartData } from "../data/mockData";

const monthly=[{name:"Mar",applications:18},{name:"Apr",applications:29},{name:"May",applications:41},{name:"Jun",applications:52},{name:"Jul",applications:67},{name:"Aug",applications:68}];

export default function Analytics() {
  return <div className="animate-float-in space-y-7"><SectionHeader title="Analytics" description="Understand what is working across your job search."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Response rate","18.4%","+2.8%",ArrowUpRight],["Interview rate","17.6%","+4.2%",Target],["Offer rate","4.4%","+1.1%",CheckCircle2],["Avg. response","5.8 days","-0.9d",Clock3]].map(([a,b,c,I])=><Card key={a} className="p-4"><I size={16} className="text-zinc-400"/><p className="mt-4 text-[11px] text-zinc-500">{a}</p><div className="mt-1 flex items-end justify-between"><span className="text-xl font-semibold">{b}</span><span className="text-[10px] font-semibold text-emerald-600">{c}</span></div></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><SectionHeader title="Application volume" description="Monthly applications."/><div className="h-64"><ResponsiveContainer><BarChart data={monthly}><CartesianGrid vertical={false} stroke="#e4e4e7"/><XAxis dataKey="name" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:10,fontSize:11}}/><Bar dataKey="applications" fill="#18181b" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card className="p-5"><SectionHeader title="Weekly conversion" description="Applications vs interviews."/><div className="h-64"><ResponsiveContainer><AreaChart data={chartData}><CartesianGrid vertical={false} stroke="#e4e4e7"/><XAxis dataKey="name" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:10,fontSize:11}}/><Area dataKey="applications" type="monotone" stroke="#18181b" fill="transparent"/><Area dataKey="interviews" type="monotone" stroke="#60a5fa" fill="transparent"/></AreaChart></ResponsiveContainer></div></Card></div><Card className="bg-zinc-950 p-6 text-white dark:bg-zinc-900"><div className="flex items-start gap-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Sparkles size={18}/></div><div><p className="text-sm font-semibold">AI career insight</p><p className="mt-2 max-w-2xl text-xs leading-5 text-zinc-400">Your interview conversion is strongest for full-stack roles. Consider prioritizing roles where React and Node.js are both listed as core requirements.</p><button className="mt-4 text-[11px] font-semibold text-white">Analyze my profile →</button></div></div></Card></div>;
}