import { ArrowLeft, CalendarDays, ExternalLink, FileText, MessageSquare, MoreHorizontal } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { applications } from "../data/mockData";
import { Badge, Button, Card, SectionHeader } from "../components/ui";

const tone={Saved:"neutral",Applied:"blue",Screening:"purple",Interview:"amber",Offer:"green",Rejected:"red"};
export default function ApplicationDetails() {
  const {id}=useParams(); const app=applications.find(a=>a.id===id)||applications[0];
  return <div className="animate-float-in space-y-6"><Link to="/applications" className="inline-flex items-center gap-2 text-xs text-zinc-500 hover:text-zinc-900 dark:hover:text-white">← Back to applications</Link>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-4"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl text-lg font-bold text-white ${app.color}`}>{app.company[0]}</div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{app.title}</h1><Badge tone={tone[app.status]}>{app.status}</Badge></div><p className="mt-1 text-sm text-zinc-500">{app.company} · {app.location}</p></div></div><div className="flex gap-2"><Button variant="secondary"><ExternalLink size={14}/> Job posting</Button><Button>Update status</Button></div></div>
    <div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="space-y-4"><Card className="p-5"><SectionHeader title="Application timeline"/><div className="space-y-6">{["Application created","Application submitted","Recruiter screening","Technical interview"].map((x,i)=><div key={x} className="flex gap-3"><div className={`mt-1 h-2.5 w-2.5 rounded-full ${i<=2?"bg-zinc-950 dark:bg-white":"bg-zinc-200 dark:bg-zinc-800"}`}/><div><p className="text-xs font-medium">{x}</p><p className="mt-1 text-[10px] text-zinc-500">{["Aug 13","Aug 12","Aug 14","Aug 18"][i]}, 2026</p></div></div>)}</div></Card><Card className="p-5"><SectionHeader title="Notes" action={<Button variant="ghost" size="sm">+ Add note</Button>}/><div className="rounded-lg bg-zinc-50 p-4 text-xs leading-5 text-zinc-600 dark:bg-zinc-900 dark:text-zinc-400">Review React performance optimization and prepare a short explanation of the recent dashboard project.</div></Card></div>
      <div className="space-y-4"><Card className="p-5"><SectionHeader title="Details"/><div className="space-y-4 text-xs">{[["Salary",app.salary],["Type",app.type],["Applied",app.applied],["Resume",app.resume]].map(([a,b])=><div key={a} className="flex justify-between gap-4"><span className="text-zinc-500">{a}</span><span className="text-right font-medium">{b}</span></div>)}</div></Card><Card className="p-5"><SectionHeader title="Skills"/><div className="flex flex-wrap gap-2">{app.skills.map(s=><span key={s} className="rounded-md border border-zinc-200 px-2 py-1 text-[10px] dark:border-zinc-800">{s}</span>)}</div></Card><Card className="p-5"><SectionHeader title="Next action"/><div className="flex gap-3"><div className="rounded-lg bg-blue-50 p-2 text-blue-600 dark:bg-blue-950/40"><CalendarDays size={15}/></div><div><p className="text-xs font-semibold">Technical interview</p><p className="mt-1 text-[10px] text-zinc-500">Aug 18 · 11:00 AM</p></div></div></Card></div>
    </div>
  </div>;
}