import { Bookmark, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Badge, Button, Card, SearchInput, SectionHeader, Select } from "../components/ui";
import { jobs } from "../data/mockData";

export default function Jobs() {
  const [q,setQ]=useState(""), [mode,setMode]=useState("All"); const nav=useNavigate();
  const filtered=useMemo(()=>jobs.filter(j=>(mode==="All"||j.mode===mode)&&(`${j.title} ${j.company} ${j.tags.join(" ")}`.toLowerCase().includes(q.toLowerCase()))),[q,mode]);
  return <div className="animate-float-in space-y-6"><SectionHeader title="Jobs" description="Discover roles that fit your current profile." action={<Button variant="secondary"><SlidersHorizontal size={15}/> More filters</Button>}/><div className="grid gap-3 md:grid-cols-[1fr_170px]"><SearchInput value={q} onChange={setQ} placeholder="Search title, company or skill..."/><Select value={mode} onChange={e=>setMode(e.target.value)}><option>All</option><option>Remote</option><option>Hybrid</option><option>On-site</option></Select></div><div className="grid gap-3 lg:grid-cols-2">{filtered.map(j=><Card key={j.id} className="p-5 transition hover:-translate-y-0.5 hover:shadow-lg hover:shadow-zinc-900/5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-bold text-white ${j.color}`}>{j.company[0]}</div><div><h3 className="text-sm font-semibold">{j.title}</h3><p className="mt-1 text-xs text-zinc-500">{j.company}</p></div></div><button className="rounded-lg p-2 text-zinc-400 hover:bg-zinc-100 dark:hover:bg-zinc-900"><Bookmark size={16} fill={j.saved?"currentColor":"none"}/></button></div><div className="mt-5 flex flex-wrap gap-2"><span className="flex items-center gap-1 text-[10px] text-zinc-500"><MapPin size={12}/>{j.location}</span><Badge>{j.mode}</Badge><Badge>{j.salary}</Badge></div><div className="mt-4 flex flex-wrap gap-1.5">{j.tags.map(t=><span key={t} className="rounded-md bg-zinc-100 px-2 py-1 text-[10px] text-zinc-600 dark:bg-zinc-900 dark:text-zinc-400">{t}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-zinc-100 pt-4 dark:border-zinc-900"><span className="text-[10px] text-zinc-400">Posted {j.posted}</span><Button size="sm" onClick={()=>nav(`/jobs/${j.id}`)}>View role →</Button></div></Card>)}</div></div>;
}