import { ArrowRight, BarChart3, BriefcaseBusiness, Check, ChevronRight, FileText, Play, Sparkles, Target, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { Button, Card } from "../components/ui";
import { applications } from "../data/mockData";

function MiniDashboard() {
  return <div className="mx-auto mt-14 max-w-6xl overflow-hidden rounded-2xl border border-zinc-200 bg-white text-left shadow-2xl shadow-zinc-900/10 dark:border-zinc-800 dark:bg-zinc-950">
    <div className="flex h-11 items-center border-b border-zinc-200 px-4 dark:border-zinc-800"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-zinc-200"/><span className="h-2.5 w-2.5 rounded-full bg-zinc-200"/><span className="h-2.5 w-2.5 rounded-full bg-zinc-200"/></div><span className="mx-auto text-[10px] text-zinc-400">app.nexora.dev/dashboard</span></div>
    <div className="grid min-h-[420px] grid-cols-[180px_1fr]">
      <div className="hidden border-r border-zinc-100 p-4 sm:block dark:border-zinc-900"><div className="mb-8 flex items-center gap-2 text-xs font-bold"><div className="grid h-6 w-6 place-items-center rounded bg-zinc-950 text-white dark:bg-white dark:text-black">N</div>nexora</div>{["Overview","Applications","Jobs","Interviews","Resumes","Analytics"].map((x,i)=><div key={x} className={`mb-1 rounded-md px-2 py-2 text-[10px] ${i===0?"bg-zinc-100 font-semibold dark:bg-zinc-900":"text-zinc-400"}`}>{x}</div>)}</div>
      <div className="p-5 sm:p-7"><div className="flex items-end justify-between"><div><p className="text-[10px] text-zinc-400">Overview</p><h3 className="mt-1 text-lg font-semibold">Good morning, Shubham</h3></div><div className="hidden rounded-md bg-zinc-950 px-3 py-2 text-[10px] text-white sm:block">+ Add application</div></div>
        <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Applications","68"],["Active","30"],["Interviews","12"],["Offers","3"]].map(([a,b])=><div key={a} className="rounded-lg border border-zinc-100 p-3 dark:border-zinc-900"><p className="text-[9px] text-zinc-400">{a}</p><p className="mt-2 text-lg font-semibold">{b}</p></div>)}</div>
        <div className="mt-5 grid gap-3 lg:grid-cols-3"><div className="h-44 rounded-lg border border-zinc-100 p-4 lg:col-span-2 dark:border-zinc-900"><p className="text-[10px] font-semibold">Applications over time</p><div className="mt-8 flex h-20 items-end gap-2">{[35,55,42,72,58,30,65,50,80,61,74,66].map((h,i)=><div key={i} className="flex-1 rounded-t bg-zinc-900/80 dark:bg-zinc-100/80" style={{height:`${h}%`}}/>)}</div></div><div className="h-44 rounded-lg border border-zinc-100 p-4 dark:border-zinc-900"><p className="text-[10px] font-semibold">Pipeline</p><div className="mt-5 space-y-3">{[["Applied","32","bg-zinc-300"],["Screening","18","bg-blue-400"],["Interview","12","bg-amber-400"],["Offer","3","bg-emerald-400"]].map(([x,n,c])=><div key={x}><div className="flex justify-between text-[9px]"><span>{x}</span><span>{n}</span></div><div className="mt-1 h-1 rounded bg-zinc-100 dark:bg-zinc-900"><div className={`h-1 rounded ${c}`} style={{width:`${Number(n)*2}%`}}/></div></div>)}</div></div></div>
      </div>
    </div>
  </div>;
}

export default function Landing() {
  return <div className="min-h-screen bg-[#fafafa] text-zinc-950 dark:bg-[#090a0c] dark:text-white">
    <nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Link to="/" className="flex items-center gap-2 text-sm font-bold"><span className="grid h-7 w-7 place-items-center rounded-lg bg-zinc-950 text-white dark:bg-white dark:text-zinc-950">N</span>nexora</Link><div className="hidden items-center gap-7 text-xs text-zinc-500 md:flex"><a href="#features">Features</a><a href="#workflow">How it works</a><a href="#ai">AI Assistant</a></div><div className="flex items-center gap-2"><Link to="/login"><Button variant="ghost" size="sm">Sign in</Button></Link><Link to="/register"><Button size="sm">Get started <ArrowRight size={14}/></Button></Link></div></nav>
    <main>
      <section className="grid-bg border-b border-zinc-200 px-5 pb-8 pt-20 text-center dark:border-zinc-800 lg:pt-28"><div className="mx-auto max-w-4xl"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-white px-3 py-1.5 text-[11px] font-medium text-zinc-600 shadow-sm dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-300"><Sparkles size={13}/> The intelligent job-search workspace</div><h1 className="mt-7 text-5xl font-semibold tracking-[-0.045em] sm:text-6xl lg:text-7xl">Your entire job search,<br/><span className="text-zinc-400">organized.</span></h1><p className="mx-auto mt-6 max-w-2xl text-sm leading-6 text-zinc-500 sm:text-base">Track applications, manage interviews, organize resumes, and understand your job search from one intelligent workspace.</p><div className="mt-8 flex justify-center gap-2"><Link to="/register"><Button size="lg">Start for free <ArrowRight size={16}/></Button></Link><Button variant="secondary" size="lg"><Play size={15}/> View demo</Button></div></div><MiniDashboard/></section>
      <section id="features" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-widest text-zinc-400">Everything in one place</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Less tab switching.<br/>More getting hired.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-200 md:grid-cols-3 dark:border-zinc-800 dark:bg-zinc-800">{[
        [BriefcaseBusiness,"Application OS","Move every opportunity through a clear pipeline from saved to offer."],
        [BarChart3,"Decision-grade analytics","See your response rate, interview conversion, and where your effort pays off."],
        [Sparkles,"AI career layer","Match resumes to roles, identify skill gaps, and prepare for interviews."]
      ].map(([Icon,title,text])=><div key={title} className="bg-[#fafafa] p-7 dark:bg-[#090a0c]"><div className="grid h-9 w-9 place-items-center rounded-lg bg-zinc-950 text-white dark:bg-white dark:text-zinc-950"><Icon size={17}/></div><h3 className="mt-7 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-zinc-500">{text}</p></div>)}</div></section>
      <section id="workflow" className="border-y border-zinc-200 bg-white px-5 py-24 dark:border-zinc-800 dark:bg-zinc-950"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-widest text-zinc-400">Built for momentum</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Turn scattered applications into a system.</h2><div className="mt-8 space-y-5">{[["01","Capture","Save a role and its details before it disappears into another browser tab."],["02","Progress","Move applications through a visual pipeline and never lose the next action."],["03","Learn","Use analytics to improve your strategy instead of applying blindly."]].map(([n,t,d])=><div key={n} className="flex gap-4"><span className="text-xs font-semibold text-zinc-300">{n}</span><div><h3 className="text-sm font-semibold">{t}</h3><p className="mt-1 text-xs leading-5 text-zinc-500">{d}</p></div></div>)}</div></div><Card className="p-6"><div className="flex items-center justify-between"><span className="text-xs font-semibold">Recent applications</span><span className="text-[10px] text-zinc-400">View all</span></div><div className="mt-4 divide-y divide-zinc-100 dark:divide-zinc-900">{applications.slice(0,5).map(a=><div key={a.id} className="flex items-center justify-between py-3"><div className="flex items-center gap-3"><span className={`grid h-7 w-7 place-items-center rounded-md text-[9px] font-bold text-white ${a.color}`}>{a.company[0]}</span><div><p className="text-xs font-medium">{a.title}</p><p className="text-[10px] text-zinc-500">{a.company}</p></div></div><span className="text-[10px] text-zinc-400">{a.status}</span></div>)}</div></Card></div></div></section>
      <section id="ai" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="rounded-3xl bg-zinc-950 p-7 text-white sm:p-12 dark:bg-zinc-900"><div className="max-w-2xl"><div className="inline-flex rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-[10px] text-zinc-300"><Sparkles size={12} className="mr-2"/> Coming with your backend</div><h2 className="mt-6 text-3xl font-semibold tracking-tight sm:text-4xl">Your career data should work for you.</h2><p className="mt-4 text-sm leading-6 text-zinc-400">Connect your future AI layer to compare resumes with job descriptions, surface missing skills, and generate focused interview preparation.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{["Resume match","Skill gaps","Interview prep"].map((x,i)=><div key={x} className="rounded-xl border border-white/10 bg-white/5 p-4"><Check size={15}/><p className="mt-4 text-xs font-medium">{x}</p><p className="mt-1 text-[10px] text-zinc-500">{["87% match score","5 skills to improve","12 likely questions"][i]}</p></div>)}</div></div></div></section>
      <section className="border-t border-zinc-200 px-5 py-20 text-center dark:border-zinc-800"><h2 className="text-3xl font-semibold tracking-tight">Ready to build your system?</h2><p className="mx-auto mt-3 max-w-md text-sm text-zinc-500">Start with a clean workspace. Add your real applications as your backend comes online.</p><Link to="/register" className="mt-7 inline-block"><Button size="lg">Create your workspace <ChevronRight size={16}/></Button></Link></section>
    </main>
    <footer className="border-t border-zinc-200 px-5 py-8 dark:border-zinc-800"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-[11px] text-zinc-400 sm:flex-row"><span>© 2026 Nexora</span><span>Built as a MERN portfolio project.</span></div></footer>
  </div>;
}